export const VEHICLE_ACTION_TYPES = {
    SET_VEHICLES: "SET_VEHICLES",
    SELECT_VEHICLE: "SELECT_VEHICLE",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    REVERT_VEHICLE_TO_INITIAL_STATE: "REVERT_VEHICLE_TO_INITIAL_STATE",
    SET_FILTERS: "SET_FILTERS",
    LOADING_VEHICLE: "LOADING_VEHICLE"
}