export const MODEL_ACTION_TYPES = {
    SET_MODELS: "SET_MODELS",
    SELECT_MODEL: "SELECT_MODEL",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    REVERT_MODEL_TO_INITIAL_STATE: "REVERT_MODEL_TO_INITIAL_STATE"
}